#!/bin/bash
# Deployment Checklist for Azure Static Web Apps

echo "📋 Azure Static Web Apps Deployment Checklist"
echo "============================================"
echo ""
echo "✅ Files created:"
echo "   - .github/workflows/azure-static-web-apps.yml"
echo "   - staticwebapp.config.json"
echo "   - server/health.ts"
echo "   - api/host.json"
echo "   - api/package.json"
echo "   - setup-azure-swa.sh"
echo ""
echo "📝 Next steps:"
echo ""
echo "1. Run the setup script to create Azure resources:"
echo "   chmod +x setup-azure-swa.sh"
echo "   ./setup-azure-swa.sh"
echo ""
echo "2. The script will automatically:"
echo "   - Create Azure Static Web App"
echo "   - Get deployment token"
echo "   - Add token to GitHub Secrets"
echo ""
echo "3. Commit and push your changes:"
echo "   git add -A"
echo "   git commit -m 'Add Azure SWA deployment pipeline'"
echo "   git push origin main"
echo ""
echo "4. Monitor deployment:"
echo "   https://github.com/jgtolentino/client/actions"
echo ""
echo "5. Once deployed, verify:"
echo "   - Frontend loads correctly"
echo "   - API health check at /api/health"
echo "   - SPA routing works (test subpages)"
echo ""
echo "Ready to deploy? Run: ./setup-azure-swa.sh"