name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          echo "=== Build Output Structure ==="
          echo "Root directory:"
          ls -la
          echo ""
          echo "Dist directory:"
          ls -la dist/ || echo "dist/ not found"
          echo ""
          echo "Finding index.html:"
          find . -name "index.html" -type f | head -10
          echo ""
          echo "=== Verifying deployment files ==="
          if [ -f "dist/index.html" ]; then
            echo "✅ dist/index.html found - deployment should work"
          elif [ -f "dist/public/index.html" ]; then
            echo "⚠️  index.html is in dist/public/ - using output_location: 'dist/public'"
          else
            echo "❌ No index.html found in expected locations"
            exit 1
          fi

      - name: Clean problematic files
        run: |
          # Remove files that cause deployment issues
          find dist -name "*.map" -type f -delete || true
          find dist -name ".DS_Store" -type f -delete || true
          find dist -name "Thumbs.db" -type f -delete || true
          find dist -name "Icon*" -type f -delete || true
          find dist -name ".*" -type f -delete || true
          # Remove any files over 100MB
          find dist -type f -size +100M -delete || true
          echo "Cleaned problematic files"

      - name: Ensure deployment config
        run: |
          # Copy staticwebapp.config.json to the output directory if it exists
          if [ -f "staticwebapp.config.json" ] && [ -f "dist/public/index.html" ]; then
            cp staticwebapp.config.json dist/public/ || true
            echo "✅ Copied staticwebapp.config.json to dist/public/"
          elif [ -f "staticwebapp.config.json" ] && [ -f "dist/index.html" ]; then
            cp staticwebapp.config.json dist/ || true
            echo "✅ Copied staticwebapp.config.json to dist/"
          fi

      - name: Final pre-deployment check
        run: |
          echo "=== Final deployment readiness check ==="
          echo "Files in dist/:"
          ls -la dist/ | head -20
          echo ""
          if [ -d "dist/public" ]; then
            echo "Files in dist/public/:"
            ls -la dist/public/ | head -20
            echo ""
            echo "Total size of dist/public/:"
            du -sh dist/public/
            echo ""
            echo "File count in dist/public/:"
            find dist/public -type f | wc -l
          fi
          echo ""
          echo "Total size of dist/:"
          du -sh dist/
          echo ""
          echo "File count in dist/:"
          find dist -type f | wc -l

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/public"  # Based on your current build output
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"