name: Azure SWA Minimal Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          
      - name: Check build output
        run: |
          echo "=== Build directory structure ==="
          find dist -type f -name "*.html" | head -10
          echo "=== Checking index.html ==="
          ls -la dist/public/index.html || echo "No index.html in dist/public"
          echo "=== Total size ==="
          du -sh dist/public

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          output_location: "../dist/public"
          skip_app_build: true